In [1]:
#list converted into numpy array
import numpy as np

my_list = [1,2,3,4,5,6]

type(np.array(my_list))

arr = np.array(my_list)

arr

array([1, 2, 3, 4, 5, 6])

In [5]:
#range & arange function are same but difference is arange fun is genrate array & range is noraml int squance
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(5) #one row five column matrix & genrating floating point value
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
#write the from of tuple and get n dimensional array
np.ones(5)
np.ones((5,5)) #genrating floating point value . in output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
# pick random value in  squence
np.random.randint(0,11)



4

In [57]:
# pick random value in from of array 4*4 matrix

np.random.randint(0,1000,(4,4))

array([[371, 925, 883,  59],
       [418, 556, 840, 249],
       [275, 638, 906,  76],
       [735, 619, 343, 896]])

In [76]:
# pick random value in  squence by they fix not change beacause ofnp.random.seed(101) function 

np.random.seed(101)

arr = np.random.randint(0,100,10)

arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [86]:


np.random.seed(101)

arr = np.random.randint(0,100,10) #arr variable add to store value

arr

print(arr.max()) #findout maximum value in array
print(arr.min()) #findout minimum value in array
print(arr.mean()) #findout averge of array
print(arr.argmax()) #findout maximum value indexing in array
print(arr.argmin()) #findout minimum value indexing in array
print(arr.reshape(2,5)) #split into rows & cloumn use reshape note:only dimensional use to exits in squence


95
9
60.8
0
7
[[95 11 81 70 63]
 [87 75  9 77 40]]


In [95]:
#example of slicing in array arrnge value by 10*10 matrix
mat = np.arange(0,100).reshape(10,10)
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [102]:
#Acessing value in array
print(mat[2,2])
print(mat[0,:]) #extract row
print(mat[:,0]) #extract column 
print(mat[0:3,0:3]) #extract 3*3 matrix


22
[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
